apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
nameSuffix: -dev
resources:
  - ../../base
  - ingress.yaml
patches:
  - target: { kind: Deployment, name: draw }
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: OBJECTS_BUCKET, value: pd-objects-dev }
images:
  - name: draw
    newName: 048751351548.dkr.ecr.us-east-2.amazonaws.com/draw
    newTag: PLACEHOLDER_SHA
