apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
nameSuffix: -dev
resources:
  - ../../base
  - ingress.yaml
images:
  - name: cwdmdc
    newName: 618402335678.dkr.ecr.us-east-2.amazonaws.com/cwdmdc
    newTag: 6cfdb82
