apiVersion: ecr.aws.upbound.io/v1beta2
kind: Repository
metadata:
  name: personal-web
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    region: us-east-2
    forceDelete: true
    imageTagMutability: MUTABLE
    imageScanningConfiguration:
      scanOnPush: true
  providerConfigRef:
    name: default
