apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws-ecr-irsa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-aws-ecr
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::618402335678:role/crossplane-provider-aws-ecr-irsa
