# KV v2 secrets engine mounted at `secret/` (path defaults to metadata.name).
# Holds static app secrets: secret/todo/dev, secret/todo/prod, ...
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: secret
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount: { name: vault-admin }
  connection: { address: "http://vault.vault.svc:8200" }
  type: kv
  options:
    version: "2"
