apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrickdwyer-com
  labels: { app: patrickdwyer-com }
spec:
  replicas: 1
  selector: { matchLabels: { app: patrickdwyer-com } }
  template:
    metadata:
      labels: { app: patrickdwyer-com }
    spec:
      containers:
        - name: nginx
          image: patrickdwyer-com
          ports:
            - containerPort: 8080
